SET NAMES 'utf8' COLLATE 'utf8mb4_0900_ai_ci';

CREATE DATABASE mydb CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;

USE mydb;

CREATE TABLE smp(id INT UNSIGNED PRIMARY KEY AUTO_INCREMENT, title VARCHAR(63) NOT NULL);

INSERT INTO smp(title) VALUES('Москва');

SELECT * FROM smp;
